name: Test Go Shared Library with Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 4: Install Nuitka
#      - name: Install Nuitka
#        run: python -m pip install --upgrade pip pyinstaller

      # Step 6: Download Go dependencies
      - name: Download Go dependencies
        run: go mod tidy

      # Step 7: Build Go shared library
      - name: Build Go shared library
        run: go build -o mylibrary.dll -buildmode=c-shared main.go
#        run: go build -o startup.dll -buildmode=c-shared
#        run: go build -o output.exe
      # Step 8: Compile Python script with Nuitka
#      - name: Compile Python script with Nuitka
#        run: |
#          pyinstaller --onefile --add-data "./startup.dll;." test_startup.py

      - name: Test compiled executable
        run: |
          python test_startup.py
        shell: cmd

      # Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
              ./output.exe
#              ./startup.dll
#              ./startup.h



